version: '3.1'

services:
  volod_telegrambot:
    depends_on:
      - vtb-db
    build:
      context: .
    environment:
      BOT_NAME: ${BOT_NAME}
      BOT_TOKEN: ${BOT_TOKEN}}
      BOT_DB_USERNAME: ${BOT_DB_USERNAME}
      BOT_DB_PASSWORD: ${BOT_DB_PASSWORD}
    restart: always
    vtb-db:
      image: mysql:5.7
      restart: always
      environment:
        MYSQL_USER: ${BOT_DB_USERNAME}
        MYSQL_PASSWORD: ${BOT_DB_PASSWORD}
        MYSQL_DATABASE: 'vtb_db'
        MYSQL_ROOT_PASSWORD: 'root'
      ports:
        - '3308:3306'
      expose:
        - '3308'
      command: --character-set-server=utf8 --collation-server=utf8_general_ci